### ISSUE TITLE
Hide gray "tap the paste" in startup

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianQRTool-iOS#41]
<img width="901" alt="image" src="https://user-images.githubusercontent.com/69103/118078444-14657c80-b36b-11eb-996b-46dace24a2f8.png">

On both Mac and iOS, iCloud items don't show up until after AppleID Auth. Instead, the empty  "tap the paste or camera button" shows up, which first time I saw I thought maybe was something broken. Additional times is annoying. Maybe just blank it, or put blank gray Summary item sized rounded rectangles with nothing in them in the background, which after AppleID will then be "filled out" with their details.

**Comment by Fonta1n3** [comment]
@ChristopherA this should be fixed in latest PR
