### ISSUE TITLE
Only "QR Tool" on Home Screen, not "Gordian QR Tool"

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianQRTool-iOS#63]
For consistency with Gordian Seed Tool, Gordian Cosigner, etc. we are not putting "Gordian" in with name and icon on the Home Screen, so not "Gordian QR Tool" but just "QR Tool".

![image](https://user-images.githubusercontent.com/69103/121640644-09256f80-ca43-11eb-8be0-dc6336587581.png)

**Comment by Fonta1n3** [comment]
"QR Tool" is taken already.

![Uploading 973E52E8-3AD0-4B28-A58D-4C3FFC33DE4C.jpeg…]()
