### ISSUE TITLE
iCloud Not Restoring

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianQRTool-iOS#67]
I tested out the ability to restore from iCloud as follows:

1. Purchased the paid store version of QR Tool
2. Added the DPAL Test QR (https://github.com/BlockchainCommons/crypto-commons/blob/master/Docs/sskr-test-vector.md)
3. Delete the app from my phone
4. Received a warning that all data on the phone would be gone, but that iCloud data would remain
5. Redownloaded the app from the store
6. Logged back in with my thumb print
7. App was empty of data

This is on an iPhone 8 running iOS 14.6

**Comment by Fonta1n3** [comment]
you have to wait aro0und 30 seconds and then manually pull to refresh or tap the refresh button.

**Comment by Fonta1n3** [comment]
I was able to replicate this and fixed it. It did not require any code changes but was an admin setting on the iCloud Kit dashboard. I have tested and the recovery worked fine via the App Store download. Closing this as I am confident its fixed, if not please raise the issue again.
