### ISSUE TITLE
App Crashes if Default Message Cell Removed

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianQRTool-iOS#72]
If you have an empty list of QRs, the app just displays "Authenticate to access your data" in cell zero. If you "Edit" that, then hit the "-" button to remove it, the app crashes.

There are three closely related bugs here.

The most critical one is:
(1) The program shouldn't crash.

Closely related:
(2) You shouldn't be able to edit until you have actual content in the list.

Much less critical, but noted:
(3) This is the wrong message. The message is supposed to be "Tap the paste or scan button to add a QR code" after you've authenticated, but before you've added anything to the list, but the logic is wrong, so that message is never used.

This issue is flagged as CRITICAL because (a) it's holding up the Mac release; and (b) it's present in the live iOS release.

**Comment by ChristopherA** [comment]
To be clear it was the Apple Mac App Store reviewers that are holding up the app due to this bug.
